/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import bendageometri.PrismaPersegiPanjang;
import bendageometri.PersegiPanjang;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class GUI_PrismaPersegiPanjang extends javax.swing.JFrame {

    /**
     * Creates new form GUI_PrismaPersegiPanjang
     */
    public GUI_PrismaPersegiPanjang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonHitungVolumedanLP = new javax.swing.JButton();
        jLabelHasilVolume = new javax.swing.JLabel();
        jLabelHasilLuasPermukaan = new javax.swing.JLabel();
        jLabelHasilLuas = new javax.swing.JLabel();
        jLabelHasilKeliling = new javax.swing.JLabel();
        jTextFieldLebar = new javax.swing.JTextField();
        jTextFieldTinggi = new javax.swing.JTextField();
        jTextFieldPanjang = new javax.swing.JTextField();
        jLabelAlas2 = new javax.swing.JLabel();
        jLabelTinggi1 = new javax.swing.JLabel();
        jLabelAlasKeliling = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonBulat = new javax.swing.JRadioButton();
        jRadioButtonDesimal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 236, 221));

        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 128, 157));
        jLabel1.setText("Prisma Persegi Panjang");

        jButtonHitungVolumedanLP.setText("Hitung");
        jButtonHitungVolumedanLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungVolumedanLPActionPerformed(evt);
            }
        });

        jLabelHasilVolume.setText("Volume Prisma Persegi Panjang : ");

        jLabelHasilLuasPermukaan.setText("Luas Permukaan Prisma Persegi Panjang : ");

        jLabelHasilLuas.setText("Luas Persegi Panjang : ");

        jLabelHasilKeliling.setText("Keliling Persegi Panjang : ");

        jLabelAlas2.setText("Panjang (cm):");

        jLabelTinggi1.setText("Tinggi Prisma (cm) : ");

        jLabelAlasKeliling.setText("Lebar (cm) :");

        jLabel2.setText("Hitung Luas Permukaan dan Volume");

        jRadioButtonBulat.setBackground(new java.awt.Color(252, 236, 221));
        buttonGroup1.add(jRadioButtonBulat);
        jRadioButtonBulat.setText("Gunakan Perhitungan bulat");
        jRadioButtonBulat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBulatActionPerformed(evt);
            }
        });

        jRadioButtonDesimal.setBackground(new java.awt.Color(252, 236, 221));
        buttonGroup1.add(jRadioButtonDesimal);
        jRadioButtonDesimal.setText("Gunakan Perhitungan Desimal");
        jRadioButtonDesimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDesimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHasilLuas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHasilKeliling, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelHasilVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 68, Short.MAX_VALUE))
                            .addComponent(jLabelHasilLuasPermukaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelAlas2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTinggi1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelAlasKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldLebar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(jButtonHitungVolumedanLP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonDesimal)
                    .addComponent(jRadioButtonBulat))
                .addGap(283, 283, 283))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButtonKembali)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(273, 273, 273)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jRadioButtonBulat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDesimal)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlasKeliling)
                    .addComponent(jTextFieldLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTinggi1)
                    .addComponent(jTextFieldTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlas2))
                .addGap(44, 44, 44)
                .addComponent(jButtonHitungVolumedanLP)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHasilVolume)
                    .addComponent(jLabelHasilLuas))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHasilLuasPermukaan)
                    .addComponent(jLabelHasilKeliling))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jButtonKembali)))
                    .addContainerGap(393, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUIPage mainPage = new GUIPage();
        mainPage.setVisible(true);
        mainPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonHitungVolumedanLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungVolumedanLPActionPerformed
        // TODO add your handling code here:
        try {
        double panjang, lebar, tinggi;

        // Ambil nilai dari TextField (anggap lo udah bikin jTextFieldPanjang, jTextFieldLebar, jTextFieldTinggi)
        if (jRadioButtonBulat.isSelected()) {
            panjang = (double) Integer.parseInt(jTextFieldPanjang.getText());
            lebar = (double) Integer.parseInt(jTextFieldLebar.getText());
            tinggi = (double) Integer.parseInt(jTextFieldTinggi.getText());
        } else if (jRadioButtonDesimal.isSelected()) {
            panjang = Double.parseDouble(jTextFieldPanjang.getText());
            lebar = Double.parseDouble(jTextFieldLebar.getText());
            tinggi = Double.parseDouble(jTextFieldTinggi.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Pilih dulu tipe input (bulat/desimal).", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi nilai
        if (panjang <= 0 || lebar <= 0 || tinggi <= 0) {
            throw new IllegalArgumentException("Semua nilai harus lebih dari 0.");
        }

        // POLYMORPHISM: pakai tipe referensi PersegiPanjang, tapi objek Prisma
        PersegiPanjang prisma = new PrismaPersegiPanjang(panjang, lebar, tinggi);
        double luasAlas = prisma.hitungLuas();
        double kelilingAlas = prisma.hitungKeliling();
        
        double volume;
        if (jRadioButtonBulat.isSelected()) {
            volume = ((PrismaPersegiPanjang) prisma).hitungVolume((int) tinggi); // pakai overloading
        } else {
            volume = prisma.hitungVolume(); // polymorphism: panggil method override dari Prisma
        }

        // Luas permukaan
        double luasPermukaan;
        if (jRadioButtonBulat.isSelected()) {
            luasPermukaan = ((PrismaPersegiPanjang) prisma).hitungLuasPermukaan((int) tinggi); // overloading
        } else {
            luasPermukaan = ((PrismaPersegiPanjang) prisma).hitungLuasPermukaan(); // polymorphism
        }

        // Output ke label
        jLabelHasilVolume.setText("Volume Prisma Persegi Panjang : " + volume + " cm³");
        jLabelHasilLuasPermukaan.setText("Luas Permukaan Prisma Persegi Panjang : " + luasPermukaan + " cm²");
        jLabelHasilKeliling.setText("Keliling Persegi Panjang: " + kelilingAlas + " cm" );
        jLabelHasilLuas.setText("Luas Persegi Panjang: " + luasAlas + " cm²" );

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid.", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Perhitungan Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonHitungVolumedanLPActionPerformed

    private void jRadioButtonBulatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBulatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBulatActionPerformed

    private void jRadioButtonDesimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDesimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDesimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_PrismaPersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_PrismaPersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_PrismaPersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_PrismaPersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_PrismaPersegiPanjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonHitungVolumedanLP;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAlas2;
    private javax.swing.JLabel jLabelAlasKeliling;
    private javax.swing.JLabel jLabelHasilKeliling;
    private javax.swing.JLabel jLabelHasilLuas;
    private javax.swing.JLabel jLabelHasilLuasPermukaan;
    private javax.swing.JLabel jLabelHasilVolume;
    private javax.swing.JLabel jLabelTinggi1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonBulat;
    private javax.swing.JRadioButton jRadioButtonDesimal;
    private javax.swing.JTextField jTextFieldLebar;
    private javax.swing.JTextField jTextFieldPanjang;
    private javax.swing.JTextField jTextFieldTinggi;
    // End of variables declaration//GEN-END:variables
}
