/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import bendageometri.JajarGenjang;
import bendageometri.Lingkaran;
import bendageometri.PrismaJajarGenjang;
import bendageometri.Tabung;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Maan
 */
public class GUI_Tabung extends javax.swing.JFrame {

    /**
     * Creates new form GUI_JajarGenjang
     */
    public GUI_Tabung() {
        initComponents();
//        updateFormBasedOnSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMethod = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jJariJariLuasPermukaanField = new javax.swing.JTextField();
        jLabelAlas = new javax.swing.JLabel();
        jLabelTinggi = new javax.swing.JLabel();
        jTinggiiLuasPermukaanField = new javax.swing.JTextField();
        jButtonHitungVolume = new javax.swing.JButton();
        jLabelHasilLuas = new javax.swing.JLabel();
        jRadioButtonAlasDanTinggi = new javax.swing.JRadioButton();
        jRadioButtonSisiDanSudut = new javax.swing.JRadioButton();
        jLabelAlasKeliling = new javax.swing.JLabel();
        jLabelTinggi1 = new javax.swing.JLabel();
        jJariJariVolumeJajarGenjangField = new javax.swing.JTextField();
        jTinggiVolumeJajarGenjangField = new javax.swing.JTextField();
        jButtonHitungLuasPermukaan = new javax.swing.JButton();
        jLabelHasilKeliling = new javax.swing.JLabel();
        jLabelHasilLuasPermukaan = new javax.swing.JLabel();
        jLabelHasilVolume = new javax.swing.JLabel();
        jButtonKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tabung");

        jLabel2.setText("Hitung Luas Permukaan");

        jLabel3.setText("Hitung Volume");

        jLabelAlas.setText("Jari-Jari (cm) :");

        jLabelTinggi.setText("Tinggi Tabung (cm) : ");

        jButtonHitungVolume.setText("Hitung");
        jButtonHitungVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungVolumeActionPerformed(evt);
            }
        });

        jLabelHasilLuas.setText("Luas Lingkaran : ");

        buttonGroupMethod.add(jRadioButtonAlasDanTinggi);
        jRadioButtonAlasDanTinggi.setSelected(true);
        jRadioButtonAlasDanTinggi.setText("Gunakan alas dan tinggi");
        jRadioButtonAlasDanTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlasDanTinggiActionPerformed(evt);
            }
        });

        buttonGroupMethod.add(jRadioButtonSisiDanSudut);
        jRadioButtonSisiDanSudut.setText("Gunakan sisi dan sudut");
        jRadioButtonSisiDanSudut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSisiDanSudutActionPerformed(evt);
            }
        });

        jLabelAlasKeliling.setText("Jari-Jari (cm) :");

        jLabelTinggi1.setText("Tinggi Tabung (cm) : ");

        jButtonHitungLuasPermukaan.setText("Hitung");
        jButtonHitungLuasPermukaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungLuasPermukaanActionPerformed(evt);
            }
        });

        jLabelHasilKeliling.setText("Keliling Lingkaran : ");

        jLabelHasilLuasPermukaan.setText("Luas Permukaan Tabung : ");

        jLabelHasilVolume.setText("Volume Tabung : ");

        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTinggiiLuasPermukaanField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jJariJariLuasPermukaanField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAlasKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTinggi1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTinggiVolumeJajarGenjangField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jJariJariVolumeJajarGenjangField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHasilLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHasilKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHasilLuasPermukaan, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonHitungLuasPermukaan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonHitungVolume)
                                    .addComponent(jLabelHasilVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSisiDanSudut, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonAlasDanTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonKembali))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonAlasDanTinggi)
                .addGap(3, 3, 3)
                .addComponent(jRadioButtonSisiDanSudut)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jJariJariLuasPermukaanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAlas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTinggi)
                            .addComponent(jTinggiiLuasPermukaanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jJariJariVolumeJajarGenjangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAlasKeliling))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTinggi1)
                            .addComponent(jTinggiVolumeJajarGenjangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButtonHitungVolume)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 128, Short.MAX_VALUE)
                        .addComponent(jButtonHitungLuasPermukaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHasilLuasPermukaan)
                            .addComponent(jLabelHasilVolume))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHasilLuas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHasilKeliling)
                        .addGap(49, 49, 49))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHitungVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungVolumeActionPerformed
        // TODO add your handling code here:
        try {
//            if (jRadioButtonAlasDanTinggi.isSelected()) {
//                // Ambil nilai alas dan tinggi
//                double alas = Double.parseDouble(jAlasJajarGenjangField.getText());
//                double tinggi = Double.parseDouble(jTinggiJajarGenjangField.getText());
//
//                // Buat objek dan hitung luas
//                JajarGenjang jajarGenjang = new JajarGenjang(alas, tinggi);
//                double luas = jajarGenjang.hitungLuas();
//
//                // Tampilkan hasil
//                jLabelHasilLuas.setText("Luas Jajar Genjang: " + luas + " cm²");
//            } else if (jRadioButtonSisiDanSudut.isSelected()) {
                // Ambil nilai alas dan tinggi
                double jariJari = Double.parseDouble(jJariJariVolumeJajarGenjangField.getText());
                double tinggiTabung = Double.parseDouble(jTinggiVolumeJajarGenjangField.getText());
//                double tinggiPrisma = Double.parseDouble(jTinggiPrismaVolumeJajarGenjangField.getText());
//                double sudut = Double.parseDouble(jSudutJajarGenjangField.getText());

                // Buat objek dan hitung luas
                Lingkaran tabung = new Tabung(jariJari, tinggiTabung);
                double volume = tabung.hitungVolume();
                double keliling = tabung.hitungKeliling();
                double luas = tabung.hitungLuas();

                // Tampilkan hasil
                jLabelHasilVolume.setText("Volume Tabung : " + volume + " cm²");
                jLabelHasilKeliling.setText("Keliling Lingkaran: " + keliling + " cm");
                jLabelHasilLuas.setText("Luas Lingkaran: " + luas + " cm");
//            } else {
//                JOptionPane.showMessageDialog(this, 
//                    "Silakan pilih metode perhitungan terlebih dahulu.", 
//                    "Pilih Metode", JOptionPane.WARNING_MESSAGE);
//            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Masukkan angka yang valid", 
                "Input Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Alas: [" + jJariJariVolumeJajarGenjangField.getText() + "]");
//System.out.println("Sisi Miring: [" + jTinggiVolumeJajarGenjangField.getText() + "]");
//System.out.println("tinggiPrisma: [" + jTinggiPrismaJajarGenjangField.getText() + "]");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, 
                e.getMessage(), 
                "Perhitungan Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonHitungVolumeActionPerformed

    private void jRadioButtonAlasDanTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlasDanTinggiActionPerformed
        // TODO add your handling code here:
//        updateFormBasedOnSelection();
    }//GEN-LAST:event_jRadioButtonAlasDanTinggiActionPerformed

    private void jRadioButtonSisiDanSudutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSisiDanSudutActionPerformed
        // TODO add your handling code here:
//        updateFormBasedOnSelection();
    }//GEN-LAST:event_jRadioButtonSisiDanSudutActionPerformed

    private void jButtonHitungLuasPermukaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungLuasPermukaanActionPerformed
        // TODO add your handling code here:
        try {
            double jariJari = Double.parseDouble(jJariJariLuasPermukaanField.getText());
            double tinggiTabung = Double.parseDouble(jTinggiiLuasPermukaanField.getText());

            // Buat objek dan hitung keliling. Validasi dilakukan di dalam class
            Lingkaran tabung = new Tabung(jariJari, tinggiTabung);
            double luasPermukaan = tabung.hitungLuasPermukaan();
            double keliling = tabung.hitungKeliling();
            double luas = tabung.hitungLuas();

            jLabelHasilLuasPermukaan.setText("Luas Permukaan Tabung : " + luasPermukaan + " cm");
            jLabelHasilKeliling.setText("Keliling Lingkaran : " + keliling + " cm");
            jLabelHasilLuas.setText("Luas Lingkaran : " + luas + " cm");
//            if (jRadioButtonAlasDanTinggi.isSelected()) {
//                double alas = Double.parseDouble(jAlasJajarGenjangField.getText());
//                double sisiMiring = Double.parseDouble(jSisiJajarGenjangField.getText());
//
//                // Buat objek dan hitung keliling. Validasi dilakukan di dalam class
//                JajarGenjang jajarGenjang = new JajarGenjang(alas, 0, sisiMiring);
//                double keliling = jajarGenjang.hitungKeliling();
//
//                jLabelHasilKeliling.setText("Keliling Jajar Genjang: " + keliling + " cm");
//
//            } else if (jRadioButtonSisiDanSudut.isSelected()) {
//                double sisiA = Double.parseDouble(jSisiAJajarGenjangField.getText());
//                double sisiB = Double.parseDouble(jSudutJajarGenjangField.getText());
//
//                // Validasi bisa juga dipindah ke method terpisah jika kamu ingin
//                double keliling = new JajarGenjang().hitungKeliling(sisiA, sisiB); 
//                jLabelHasilKeliling.setText("Keliling Jajar Genjang: " + keliling + " cm");
//
//            } else {
//                JOptionPane.showMessageDialog(this,
//                    "Silakan pilih metode perhitungan terlebih dahulu.",
//                    "Pilih Metode", JOptionPane.WARNING_MESSAGE);
//            }


        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Masukkan angka yang valid untuk sisi atau alas.",
                "Input Error", JOptionPane.ERROR_MESSAGE);
//                        System.out.println("Alas: [" + jJariJariLuasPermukaanField.getText() + "]");
//System.out.println("Sisi Miring: [" + jTinggiVolumeJajarGenjangField.getText() + "]");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Perhitungan Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonHitungLuasPermukaanActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUIPage mainPage = new GUIPage();
        mainPage.setVisible(true);
        mainPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

//    private void updateFormBasedOnSelection() {
//        boolean isAlasTinggi = jRadioButtonAlasDanTinggi.isSelected();
//        boolean isSisiSudut = jRadioButtonSisiDanSudut.isSelected();
//
//        // Alas & Tinggi
//        jLabelAlas.setVisible(isAlasTinggi); 
//        jAlasJajarGenjangField.setVisible(isAlasTinggi);
//        jLabelTinggi.setVisible(isAlasTinggi); 
//        jTinggiJajarGenjangField.setVisible(isAlasTinggi);
//
//        // Sisi & Sudut (misal jLabel6 dan jLabel7 untuk sisi & sudut)
//        jLabelSisiA.setVisible(isSisiSudut);
//        jSisiMiringLuasPermukaanJajarGenjangField.setVisible(isSisiSudut);
//        jLabelSisiB.setVisible(isSisiSudut);
//        jTinggiPrismaJajarGenjangField.setVisible(isSisiSudut);
////        jLabelSudut.setVisible(isSisiSudut);
////        jSudutJajarGenjangField.setVisible(isSisiSudut);
//    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Tabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Tabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Tabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Tabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Tabung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMethod;
    private javax.swing.JButton jButtonHitungLuasPermukaan;
    private javax.swing.JButton jButtonHitungVolume;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JTextField jJariJariLuasPermukaanField;
    private javax.swing.JTextField jJariJariVolumeJajarGenjangField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAlas;
    private javax.swing.JLabel jLabelAlasKeliling;
    private javax.swing.JLabel jLabelHasilKeliling;
    private javax.swing.JLabel jLabelHasilLuas;
    private javax.swing.JLabel jLabelHasilLuasPermukaan;
    private javax.swing.JLabel jLabelHasilVolume;
    private javax.swing.JLabel jLabelTinggi;
    private javax.swing.JLabel jLabelTinggi1;
    private javax.swing.JRadioButton jRadioButtonAlasDanTinggi;
    private javax.swing.JRadioButton jRadioButtonSisiDanSudut;
    private javax.swing.JTextField jTinggiVolumeJajarGenjangField;
    private javax.swing.JTextField jTinggiiLuasPermukaanField;
    // End of variables declaration//GEN-END:variables
}
