/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import bendageometri.LayangLayang;
import bendageometri.PrismaLayangLayang;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class GUI_PrismaLayangLayang extends javax.swing.JFrame {

    /**
     * Creates new form GUI_PersegiPanjang
     */
    public GUI_PrismaLayangLayang() {
        initComponents();
//        updateFormBasedOnSelection();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radioButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonKembali1 = new javax.swing.JButton();
        jLabelDiagonal1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDiagonal1Field = new javax.swing.JTextField();
        jLabelDiagonal2 = new javax.swing.JLabel();
        jDiagonal2Field = new javax.swing.JTextField();
        jButtonHitungVolumeLuas = new javax.swing.JButton();
        jLabelHasilVolume = new javax.swing.JLabel();
        jLabelHasilLuasPermukaan = new javax.swing.JLabel();
        jLabelDiagonal3 = new javax.swing.JLabel();
        jTinggiField = new javax.swing.JTextField();
        jRadioButtonDesimal = new javax.swing.JRadioButton();
        jRadioButtonBulat = new javax.swing.JRadioButton();
        jLabelDiagonal4 = new javax.swing.JLabel();
        jSisi1Field = new javax.swing.JTextField();
        jLabelDiagonal5 = new javax.swing.JLabel();
        jSisi2Field = new javax.swing.JTextField();

        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });

        jLabel2.setText("Hitung Luas");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 236, 221));

        jLabel1.setBackground(new java.awt.Color(0, 128, 157));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 128, 157));
        jLabel1.setText("Prisma Layang-Layang");

        jButtonKembali1.setText("Kembali");
        jButtonKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembali1ActionPerformed(evt);
            }
        });

        jLabelDiagonal1.setText("Diagonal 1 (cm) :");

        jLabel3.setText("Hitung Volume dan Luas Permukaan");

        jLabelDiagonal2.setText("Diagonal 2 (cm) : ");

        jButtonHitungVolumeLuas.setText("Hitung");
        jButtonHitungVolumeLuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungVolumeLuasActionPerformed(evt);
            }
        });

        jLabelHasilVolume.setText("Volume Prisma Layang-Layang: ");

        jLabelHasilLuasPermukaan.setText("Luas Permukaan Prisma Layang-Layang : ");

        jLabelDiagonal3.setText("Tinggi Prisma (cm) : ");

        radioButton.add(jRadioButtonDesimal);
        jRadioButtonDesimal.setText("Gunakan bilangan desimal");
        jRadioButtonDesimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDesimalActionPerformed(evt);
            }
        });

        radioButton.add(jRadioButtonBulat);
        jRadioButtonBulat.setText("Gunakan bilangan bulat");
        jRadioButtonBulat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBulatActionPerformed(evt);
            }
        });

        jLabelDiagonal4.setText("Sisi 1 (cm) :");

        jLabelDiagonal5.setText("Sisi 2 (cm) : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButtonKembali1)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonHitungVolumeLuas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelHasilLuasPermukaan, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelHasilVolume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelDiagonal4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSisi1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabelDiagonal5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSisi2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadioButtonDesimal)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelDiagonal1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDiagonal1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(67, 67, 67)
                                                .addComponent(jLabelDiagonal2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDiagonal2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addComponent(jLabelDiagonal3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTinggiField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jRadioButtonBulat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDesimal)
                    .addComponent(jRadioButtonBulat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDiagonal1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDiagonal1)
                    .addComponent(jLabelDiagonal2)
                    .addComponent(jDiagonal2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDiagonal3)
                    .addComponent(jTinggiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSisi1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDiagonal4)
                    .addComponent(jLabelDiagonal5)
                    .addComponent(jSisi2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabelHasilVolume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHasilLuasPermukaan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKembali1)
                    .addComponent(jButtonHitungVolumeLuas))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    private void updateFormBasedOnSelection() {
//        // Panjang lebar
//        jLabelPanjang.setVisible(isVisible(true)); 
//        jLabelLebar.setVisible(isVisible(true)); 
//
//    }
    
    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUIPage mainPage = new GUIPage();
        mainPage.setVisible(true);
        mainPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembali1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUIPage mainPage = new GUIPage();
        mainPage.setVisible(true);
        mainPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonKembali1ActionPerformed

    private void jButtonHitungVolumeLuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungVolumeLuasActionPerformed
        try {
    if (jRadioButtonDesimal.isSelected()) {
        // Ambil input dari field dan parsing ke double
        double diagonal1 = Double.parseDouble(jDiagonal1Field.getText());
        double diagonal2 = Double.parseDouble(jDiagonal2Field.getText());
        double sisi1 = Double.parseDouble(jSisi1Field.getText());
        double sisi2 = Double.parseDouble(jSisi2Field.getText());
        double tinggi = Double.parseDouble(jTinggiField.getText());

        // Buat objek prisma dengan overloading
        PrismaLayangLayang prisma = new PrismaLayangLayang(diagonal1, diagonal2, sisi1, sisi2, tinggi);

        double volume = prisma.hitungVolume(diagonal1, diagonal2, tinggi); // method overloading
        double luasPermukaan = prisma.hitungLuasPermukaan(diagonal1, diagonal2, sisi1, sisi2, tinggi); // method overloading

        // Tampilkan hasil
        jLabelHasilVolume.setText("Volume Prisma Layang-Layang       : " + String.format("%.2f", volume) + " cm³");
        jLabelHasilLuasPermukaan.setText("Luas Permukaan Prisma Layang-Layang : " + String.format("%.2f", luasPermukaan) + " cm²");

    } else if (jRadioButtonBulat.isSelected()) {
        // Ambil input dan parsing ke int, lalu ke double (karena parameter butuh double)
        int diagonal1 = Integer.parseInt(jDiagonal1Field.getText());
        int diagonal2 = Integer.parseInt(jDiagonal2Field.getText());
        int sisi1 = Integer.parseInt(jSisi1Field.getText());
        int sisi2 = Integer.parseInt(jSisi2Field.getText());
        int tinggi = Integer.parseInt(jTinggiField.getText());

        // Buat objek prisma dan gunakan method override
        PrismaLayangLayang prisma = new PrismaLayangLayang(diagonal1, diagonal2, sisi1, sisi2, tinggi);

        double volume = prisma.hitungVolume(); // override tanpa parameter
        double luasPermukaan = prisma.hitungLuasPermukaan(); // override tanpa parameter

        // Tampilkan hasil
        jLabelHasilVolume.setText("Volume Prisma Layang-Layang       : " + String.format("%.2f", volume) + " cm³");
        jLabelHasilLuasPermukaan.setText("Luas Permukaan Prisma Layang-Layang : " + String.format("%.2f", luasPermukaan) + " cm²");
    }

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this,
        "Masukkan angka yang valid untuk diagonal, sisi, dan tinggi.",
        "Input Error", JOptionPane.ERROR_MESSAGE);

} catch (IllegalArgumentException e) {
    JOptionPane.showMessageDialog(this,
        e.getMessage(),
        "Perhitungan Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButtonHitungVolumeLuasActionPerformed

    private void jRadioButtonDesimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDesimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDesimalActionPerformed

    private void jRadioButtonBulatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBulatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBulatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_PrismaLayangLayang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_PrismaLayangLayang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_PrismaLayangLayang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_PrismaLayangLayang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_PrismaLayangLayang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHitungVolumeLuas;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonKembali1;
    private javax.swing.JTextField jDiagonal1Field;
    private javax.swing.JTextField jDiagonal2Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDiagonal1;
    private javax.swing.JLabel jLabelDiagonal2;
    private javax.swing.JLabel jLabelDiagonal3;
    private javax.swing.JLabel jLabelDiagonal4;
    private javax.swing.JLabel jLabelDiagonal5;
    private javax.swing.JLabel jLabelHasilLuasPermukaan;
    private javax.swing.JLabel jLabelHasilVolume;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonBulat;
    private javax.swing.JRadioButton jRadioButtonDesimal;
    private javax.swing.JTextField jSisi1Field;
    private javax.swing.JTextField jSisi2Field;
    private javax.swing.JTextField jTinggiField;
    private javax.swing.ButtonGroup radioButton;
    // End of variables declaration//GEN-END:variables
}
