/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Maan
 */
public class GUIPage extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUIPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonTembereng = new javax.swing.JButton();
        jButtonJajarGenjang = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonTabung = new javax.swing.JButton();
        jButtonBola = new javax.swing.JButton();
        jButtonLayangLayang1 = new javax.swing.JButton();
        jButtonPersegiPanjang = new javax.swing.JButton();
        jButtonLingkaran = new javax.swing.JButton();
        jButtonLimasPersegiPanjang = new javax.swing.JButton();
        jButtonPrismaPersegiPanjang = new javax.swing.JButton();
        jButtonKerucut = new javax.swing.JButton();
        jButtonBelahKetupat = new javax.swing.JButton();
        jButtonJuringLingkaran = new javax.swing.JButton();
        jButtonPrismaBelahKetupat = new javax.swing.JButton();
        jButtonLimasBelahKetupat = new javax.swing.JButton();
        jButtonLimasBelahKetupat1 = new javax.swing.JButton();
        jButtonLimasJajarGenjang = new javax.swing.JButton();
        jButtonLimasTrapesium = new javax.swing.JButton();
        jButtonLimasLayangLayang = new javax.swing.JButton();
        jButtonJuringBola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("*** BANGUN DATAR (2D) ***");

        jLabel2.setText("*** BANGUN RUANG (3D) ***");

        jButtonTembereng.setText("Tembereng Lingkaran");
        jButtonTembereng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTemberengActionPerformed(evt);
            }
        });

        jButtonJajarGenjang.setText("Jajar Genjang");
        jButtonJajarGenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJajarGenjangActionPerformed(evt);
            }
        });

        jButton3.setText("Prisma Jajar Genjang");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonTabung.setText("Tabung");
        jButtonTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabungActionPerformed(evt);
            }
        });

        jButtonBola.setText("Bola");
        jButtonBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBolaActionPerformed(evt);
            }
        });

        jButtonLayangLayang1.setText("Layang-Layang");
        jButtonLayangLayang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayangLayang1ActionPerformed(evt);
            }
        });

        jButtonPersegiPanjang.setText("Persegi Panjang");
        jButtonPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersegiPanjangActionPerformed(evt);
            }
        });

        jButtonLingkaran.setText("Lingkaran");
        jButtonLingkaran.setToolTipText("");
        jButtonLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLingkaranActionPerformed(evt);
            }
        });

        jButtonLimasPersegiPanjang.setText("Limas Persegi Panjang");
        jButtonLimasPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimasPersegiPanjangActionPerformed(evt);
            }
        });

        jButtonPrismaPersegiPanjang.setText("Prisma Persegi Panjang");
        jButtonPrismaPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrismaPersegiPanjangActionPerformed(evt);
            }
        });

        jButtonKerucut.setText("Kerucut");
        jButtonKerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKerucutActionPerformed(evt);
            }
        });

        jButtonBelahKetupat.setText("Belah Ketupat");
        jButtonBelahKetupat.setToolTipText("");
        jButtonBelahKetupat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBelahKetupatActionPerformed(evt);
            }
        });

        jButtonJuringLingkaran.setText("Juring Lingkaran");
        jButtonJuringLingkaran.setToolTipText("");
        jButtonJuringLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJuringLingkaranActionPerformed(evt);
            }
        });

        jButtonPrismaBelahKetupat.setText("Prisma Belah Ketupat");
        jButtonPrismaBelahKetupat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrismaBelahKetupatActionPerformed(evt);
            }
        });

        jButtonLimasBelahKetupat.setText("Limas Belah Ketupat");
        jButtonLimasBelahKetupat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimasBelahKetupatActionPerformed(evt);
            }
        });

        jButtonLimasBelahKetupat1.setText("Kerucut Terpancung");
        jButtonLimasBelahKetupat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimasBelahKetupat1ActionPerformed(evt);
            }
        });

        jButtonLimasJajarGenjang.setText("Limas Jajar Genjang");
        jButtonLimasJajarGenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimasJajarGenjangActionPerformed(evt);
            }
        });

        jButtonLimasTrapesium.setText("Limas Trapesium");
        jButtonLimasTrapesium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimasTrapesiumActionPerformed(evt);
            }
        });

        jButtonLimasLayangLayang.setText("Limas Layang-Layang");
        jButtonLimasLayangLayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimasLayangLayangActionPerformed(evt);
            }
        });

        jButtonJuringBola.setText("Juring Bola");
        jButtonJuringBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJuringBolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonJajarGenjang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTembereng, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLayangLayang1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPersegiPanjang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLingkaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBelahKetupat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonJuringLingkaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonBola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTabung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimasPersegiPanjang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrismaPersegiPanjang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonKerucut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrismaBelahKetupat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimasBelahKetupat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimasBelahKetupat1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimasJajarGenjang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimasTrapesium, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimasLayangLayang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonJuringBola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJajarGenjang)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTembereng)
                    .addComponent(jButtonTabung))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBola)
                    .addComponent(jButtonLayangLayang1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPersegiPanjang)
                    .addComponent(jButtonLimasPersegiPanjang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLingkaran)
                    .addComponent(jButtonPrismaPersegiPanjang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKerucut)
                    .addComponent(jButtonBelahKetupat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJuringLingkaran)
                    .addComponent(jButtonPrismaBelahKetupat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimasBelahKetupat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimasBelahKetupat1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimasJajarGenjang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimasTrapesium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimasLayangLayang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonJuringBola)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJajarGenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJajarGenjangActionPerformed
        // TODO add your handling code here:
        GUI_JajarGenjang jajarGenjangPage = new GUI_JajarGenjang();
        jajarGenjangPage.setVisible(true);
        jajarGenjangPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonJajarGenjangActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        GUI_PrismaJajarGenjang prismJajarGenjangPage = new GUI_PrismaJajarGenjang();
        prismJajarGenjangPage.setVisible(true);
        prismJajarGenjangPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabungActionPerformed
        // TODO add your handling code here:
        GUI_Tabung tabungPage = new GUI_Tabung();
        tabungPage.setVisible(true);
        tabungPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonTabungActionPerformed

    private void jButtonBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBolaActionPerformed
        // TODO add your handling code here:
        GUI_Bola bolaPage = new GUI_Bola();
        bolaPage.setVisible(true);
        bolaPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonBolaActionPerformed

    private void jButtonTemberengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTemberengActionPerformed
        // TODO add your handling code here:
        GUI_TemberengLingkaran temberengPage = new GUI_TemberengLingkaran();
        temberengPage.setVisible(true);
        temberengPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonTemberengActionPerformed

    private void jButtonLayangLayang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayangLayang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLayangLayang1ActionPerformed

    private void jButtonPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersegiPanjangActionPerformed
        // TODO add your handling code here:
        GUI_PersegiPanjang persegiPanjangPage = new GUI_PersegiPanjang();
        persegiPanjangPage.setVisible(true);
        persegiPanjangPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonPersegiPanjangActionPerformed

    private void jButtonLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLingkaranActionPerformed
        // TODO add your handling code here:
        GUI_Lingkaran lingkaranPage = new GUI_Lingkaran();
        lingkaranPage.setVisible(true);
        lingkaranPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonLingkaranActionPerformed

    private void jButtonLimasPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimasPersegiPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimasPersegiPanjangActionPerformed

    private void jButtonPrismaPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrismaPersegiPanjangActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_jButtonPrismaPersegiPanjangActionPerformed

    private void jButtonKerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKerucutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKerucutActionPerformed

    private void jButtonBelahKetupatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBelahKetupatActionPerformed
        // TODO add your handling code here:
        GUI_BelahKetupat belahKetupatPage = new GUI_BelahKetupat();
        belahKetupatPage.setVisible(true);
        belahKetupatPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonBelahKetupatActionPerformed

    private void jButtonJuringLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJuringLingkaranActionPerformed
        // TODO add your handling code here:
        GUI_JuringLingkaran juringLingkaranPage = new GUI_JuringLingkaran();
        juringLingkaranPage.setVisible(true);
        juringLingkaranPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonJuringLingkaranActionPerformed

    private void jButtonPrismaBelahKetupatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrismaBelahKetupatActionPerformed
        // TODO add your handling code here:
        GUI_PrismaBelahKetupat prismaBelahKetupatPage = new GUI_PrismaBelahKetupat();
        prismaBelahKetupatPage.setVisible(true);
        prismaBelahKetupatPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonPrismaBelahKetupatActionPerformed

    private void jButtonLimasBelahKetupatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimasBelahKetupatActionPerformed
        // TODO add your handling code here:
        GUI_LimasBelahKetupat limasBelahKetupatPage = new GUI_LimasBelahKetupat();
        limasBelahKetupatPage.setVisible(true);
        limasBelahKetupatPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonLimasBelahKetupatActionPerformed

    private void jButtonLimasBelahKetupat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimasBelahKetupat1ActionPerformed
        // TODO add your handling code here:
        GUI_KerucutTerpancung ktpPage = new GUI_KerucutTerpancung();
        ktpPage.setVisible(true);
        ktpPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonLimasBelahKetupat1ActionPerformed

    private void jButtonLimasJajarGenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimasJajarGenjangActionPerformed
        
        // TODO add your handling code here:
        GUI_LimasJajarGenjang ktpPage = new GUI_LimasJajarGenjang();
        ktpPage.setVisible(true);
        ktpPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonLimasJajarGenjangActionPerformed

    private void jButtonLimasTrapesiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimasTrapesiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimasTrapesiumActionPerformed

    private void jButtonLimasLayangLayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimasLayangLayangActionPerformed
        // TODO add your handling code here:
        GUI_LimasLayangLayang ktpPage = new GUI_LimasLayangLayang();
        ktpPage.setVisible(true);
        ktpPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonLimasLayangLayangActionPerformed

    private void jButtonJuringBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJuringBolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJuringBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBelahKetupat;
    private javax.swing.JButton jButtonBola;
    private javax.swing.JButton jButtonJajarGenjang;
    private javax.swing.JButton jButtonJuringBola;
    private javax.swing.JButton jButtonJuringLingkaran;
    private javax.swing.JButton jButtonKerucut;
    private javax.swing.JButton jButtonLayangLayang1;
    private javax.swing.JButton jButtonLimasBelahKetupat;
    private javax.swing.JButton jButtonLimasBelahKetupat1;
    private javax.swing.JButton jButtonLimasJajarGenjang;
    private javax.swing.JButton jButtonLimasLayangLayang;
    private javax.swing.JButton jButtonLimasPersegiPanjang;
    private javax.swing.JButton jButtonLimasTrapesium;
    private javax.swing.JButton jButtonLingkaran;
    private javax.swing.JButton jButtonPersegiPanjang;
    private javax.swing.JButton jButtonPrismaBelahKetupat;
    private javax.swing.JButton jButtonPrismaPersegiPanjang;
    private javax.swing.JButton jButtonTabung;
    private javax.swing.JButton jButtonTembereng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
